Init guides
ember-best-practices/jquery-avoidance-techniques pull request #1
Opened 2017-08-14 18:50 UTC by lynchbomb

This PR is a starting point and includes basic vanilla JS parity methods with a brief explanation. The final goal being a full list avoidance techniques for all jQuery methods.

2017-08-14 21:19 UTC, nlfurniss commented on guides/animate.md
> +Use CSS animations instead toggled with JS classList#.
Seems to be missing the last part: `Use CSS animations instead toggled with JS classList#add and classList#remove.`

2017-08-14 21:19 UTC, nlfurniss commented on guides/add-class.md
> +```
This animation stuff is already in the `animate`

2017-08-14 21:19 UTC, nlfurniss commented on guides/add-class.md
> +Use CSS animations instead toggled with JS classList#add and classList#remove.
Seems like copy/paste from `animate`?

2017-08-14 21:19 UTC, nlfurniss commented on guides/closest.md
> +Use closest instead.
Should note there is no IE11 support. Good candidate for util?

2017-08-14 21:19 UTC, nlfurniss commented on guides/css.md
> +Use getComputedStyle instead.
Should note that `getcomputedstyle` triggers reflow/recalc

https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getcomputedstyle

2017-08-14 21:19 UTC, nlfurniss commented on guides/css.md
> +Use getComputedStyle instead.
There is also `style`, which usually makes a lot more sense than `GCS`, like in your example:

`elem.style.color`

It also covers how to set css props, which `$.css` does as well

2017-08-14 21:56 UTC, lynchbomb commented
Yeah appears this is missing an amended commit. I'll update.

2017-08-14 23:01 UTC, nlfurniss reviewed
Looks good!

2017-08-14 23:01 UTC, nlfurniss commented on guides/css.md
> +
Think we should suggest `style` as a way to get styles as option 1, since for most cases it works and is less costly.

2017-08-15 01:12 UTC, trentmwillis requested changes
What is the advantage of this repo over just referring people to [youmightnotneedjquery](http://youmightnotneedjquery.com/)? We should outline the reasons for this repo and what it aims to accomplish in the `README`.

2017-08-15 02:50 UTC, lynchbomb commented
http://youmightnotneedjquery.com/ is very helpful indeed and covers many use-cases. 
The goal of this repo is to provide a deeper knowledge base with more robust examples, modern ES2016+ alternatives to jQuery, provide examples that are more specific to Ember applications with Util functions as well as cover all/most of the methods within jQuery.

2017-08-16 05:19 UTC, trentmwillis commented
> The goal of this repo is to provide a deeper knowledge base with more robust examples, modern ES2016+ alternatives to jQuery, provide examples that are more specific to Ember applications with Util functions as well as cover all/most of the methods within jQuery.

:+1: We should include this as a brief description in the `README.md`

2017-08-16 22:27 UTC, merged